# Generated by Django 5.0.4 on 2024-04-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Order',
        ),
    ]
