# Generated by Django 5.0.4 on 2024-04-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='Food_Items',
        ),
    ]
