# Generated by Django 5.0.4 on 2024-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_menu_food_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_price', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Food_Items',
        ),
    ]
